import Head from 'next/head';
import MainLayout from '../components/MainLayout';

export default function Home() {
  return (
    <>
      <Head>
        <title>Expenses Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>CONTENT</MainLayout>
    </>
  );
}
