import { Typography } from 'antd';
import Head from 'next/head';
import CenterWrapper from '../components/CenterWrapper';

export default function Home() {
  return (
    <>
      <Head>
        <title>Expenses Tracke</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <CenterWrapper>
        <Typography.Title>HOME</Typography.Title>
      </CenterWrapper>
    </>
  );
}
