import Head from 'next/head';
import { parse } from 'cookie';
import MainLayout from '../components/MainLayout';
import { COOKIE_NAME } from '@/constants/auth';
import { Typography } from 'antd';
import Link from 'next/link';
import RoundCornerButton from '../components/RoundCornerButton';

export const getServerSideProps = context => {
  const cookies = parse(context.req.headers?.cookie ?? '');
  const hasLoggedIn = Boolean(cookies[COOKIE_NAME]);
  return {
    props: {
      hasLoggedIn
    }
  };
};

export default function Home({ hasLoggedIn }) {
  const redirectUrl = hasLoggedIn ? 'expenses' : '/login';
  const buttonLabel = hasLoggedIn ? 'Expenses' : 'Get Started';

  return (
    <>
      <Head>
        <title>Expenses Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout hasLoggedIn={hasLoggedIn} hasAuthButton={true}>
        <div style={{ display: 'flex', justifyContent: 'center' }}>
          <Typography.Title level={3} style={{ textAlign: 'center' }}>
            Track your expenses everyday
          </Typography.Title>
        </div>
        <div
          style={{
            display: 'flex',
            justifyContent: 'center',
            marginTop: '24px'
          }}
        >
          <Link href={redirectUrl}>
            <a>
              <RoundCornerButton
                type="primary"
                style={{ backgroundColor: '#064274', height: '40px' }}
              >
                {buttonLabel}
              </RoundCornerButton>
            </a>
          </Link>
        </div>
      </MainLayout>
    </>
  );
}
